// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_bits
std::vector< int > get_bits(unsigned long x);
RcppExport SEXP NewPackage_get_bits(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< unsigned long >::type x(xSEXP);
    __result = Rcpp::wrap(get_bits(x));
    return __result;
END_RCPP
}
// bf_cpp
List bf_cpp(NumericMatrix x, int W);
RcppExport SEXP NewPackage_bf_cpp(SEXP xSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type W(WSEXP);
    __result = Rcpp::wrap(bf_cpp(x, W));
    return __result;
END_RCPP
}
